/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import base.*;
import stat.*;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Pafel
 */
public class IllumiChat extends javax.swing.JFrame 
{
    Base base = new Base("base.txt");
    Stat stat = new Stat();
    private int indexprev = -1;
    /**
     * Creates new form NewJFrame
     */
    public IllumiChat() throws IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatOut = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        statArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        chatIn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IllumiChat");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));

        chatOut.setEditable(false);
        chatOut.setColumns(20);
        chatOut.setRows(5);
        chatOut.setFocusable(false);
        chatOut.setMinimumSize(new java.awt.Dimension(1, 1));
        chatOut.setName(""); // NOI18N
        jScrollPane1.setViewportView(chatOut);

        statArea.setEditable(false);
        statArea.setColumns(20);
        statArea.setRows(5);
        statArea.setFocusable(false);
        jScrollPane2.setViewportView(statArea);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Statystyki");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        chatIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatIn, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chatIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            base.saveToTheFile("base.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(IllumiChat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void chatInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatInActionPerformed

        chatOut.append("Ty: " + chatIn.getText() + "\n");
        String word1 = null;
        String word2 = null;

        int i = 0;

        String[] parts = chatIn.getText().split(" ");

        for (String s : parts) {
            if (i == 0) {
                word1 = s;
                if (word1.length() == chatIn.getText().length())
                    indexprev = base.addGram(indexprev, word1, "*");
                i++;
            }

            else if (i == 1) {
                word2 = s;
                indexprev = base.addGram(indexprev, word1, word2);
                i++;
            }

            else {
                word1 = word2;
                word2 = s;
                indexprev = base.addGram(indexprev, word1, word2);
            }
        }

        StringBuilder b = new StringBuilder(100);
        int r = base.randomIndex(indexprev);
        if (r != -1) {
            b.append(base.firstGramWord(r));
            stat.addToStat(base.firstGramWord(r) + " " + base.lastGramWord(r));
            if (base.lastGramWord(r) != "*") {
                
                b.append(" ").append(base.lastGramWord(r));
                
                while (isEnd(base.lastGramWord(r)) != 0) {
                    r = base.randomIndex(r);
                    
                    if (base.lastGramWord(r) != "*") {
                        
                        b.append(" ").append(base.lastGramWord(r));
                        stat.addToStat(base.firstGramWord(r) + " " + base.lastGramWord(r));
                    }
                }
            }
            indexprev = r;
            statArea.setText("");
            statArea.append(stat.statText().toString());
        }

        else
            b.append("Teach me Senpai!!!");

        chatOut.append("IllumiChan: " + b.toString() + "\n");
        chatIn.setText("");
    }//GEN-LAST:event_chatInActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    
    public static void main(String[] args) throws IOException {
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IllumiChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IllumiChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IllumiChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IllumiChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        int currentindex = 0;
        
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new IllumiChat().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(IllumiChat.class.getName()).log(Level.SEVERE, null, ex);
            }
        }); 
    }

    
    private static int isEnd(String word) {
        for (char c : word.toCharArray()) {
            if (c == '.' || c == '?' || c == '!' || c == '*')
                return 0;
        }
        return 1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chatIn;
    private javax.swing.JTextArea chatOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea statArea;
    // End of variables declaration//GEN-END:variables
}